### ISSUE TITLE
STATUSMSGs are handled incorrectly

### ISSUE THREAD

**Issue by Mikaela** [communi/communi-sailfish#100]
If I send STATUSMSG to opped or higher `/msg @#channel hi`, communi-sailfish opens a new channel window `@#channel` where the message is shown instead of showing it on correct channel.

See also:
* https://github.com/hexchat/hexchat/issues/1246
* https://github.com/erming/shout/issues/317

**Comment by jpnurmi** [comment]
STATUSMSGs are now delivered to the right window, but the visual distinction part is still missing.

**Comment by Mikaela** [comment]
How about STATUSNOTICEs?

**Comment by jpnurmi** [comment]
Yes, STATUSMSG prefixes are handled for both PRIVMSGs and NOTICEs.

**Comment by Mikaela** [comment]
HexChat has the same issue https://github.com/hexchat/hexchat/issues/1246.
