### ISSUE TITLE
Feature request: allow sorting channels by activity

### ISSUE THREAD

**Issue by Mikaela** [communi/communi-sailfish#101]
In the channel list. Cover already does this.

**Comment by jpnurmi** [comment]
Are you sure you want this? With plenty of active channels, the list keeps shuffling constantly...

**Comment by rburchell** [comment]
That's the way I used to use irssi at least. Meta+a to switch to the most recently active window, list ordered by activity. So yes, I'd love it :)

**Comment by jpnurmi** [comment]
Fair enough, will be available in the upcoming version 0.9 :)
