### ISSUE TITLE
Using earbuds the highlight sound makes me deaf

### ISSUE THREAD

**Issue by Mikaela** [communi/communi-sailfish#102]
Aspergers syndrome with oversensitive hearing probably makes it worse

**Comment by Mikaela** [comment]
After talking on \#communi at freenode I am not sure if this should  be closed as this is Sailfish issue.

It's discussed at https://together.jolla.com/question/78885/idea-independent-system-sound-level-adjustment/

**Comment by jpnurmi** [comment]
I've added a setting option to disable the notification sound altogether. The rest is up to Sailfish...
