### ISSUE TITLE
Suppress `/who` output in channels

### ISSUE THREAD

**Issue by Ram-Z** [communi/communi-sailfish#104]
Redirect the output of the `/who` command to the network channel instead of showing it in the corresponding channel.

The rationale is that when you have a client like weechat (which will regularly send /who commands no check for away status) connected to the same bouncer as this client you get a lot of noise in the channel.

**Comment by jpnurmi** [comment]
I don't know which bouncer you're using, but ZNC has a module (http://wiki.znc.in/Route_replies) that fixes the whole problem.

**Comment by Ram-Z** [comment]
I musst have missed that module. Disregard this issue then, thanks!
