### ISSUE TITLE
[Should be easy & fast] Request echo-message instead of znc.in/echo-message

### ISSUE THREAD

**Issue by Mikaela** [communi/communi-sailfish#115]
- https://github.com/znc/znc/pull/950#issuecomment-96507907

The znc.in/echo-message only existed in old version of [playback](http://wiki.znc.in/Playback) module for ZNC. When it became officialaly supported by ZNC, it was removed from [playback](http://wiki.znc.in/Playback) and renamed into `echo-message` which is the name all IRCv3 servers use.

**Comment by Mikaela** [comment]
It seems I also asked this at IRC before this issue tracker was reopened.

```
2015-08-06.log:[12:05:44] <Mikaela> Venemo: hi, jpnurmi asked me to ask you if you could release new testing version or something of Communi Sailfish with znc.in/echo-message capability renamed as echo-message
2015-08-06.log:[12:05:44] <Mikaela> (I am not fully sure which capability it was as I have been away for some time and you were in my /notify)
2015-08-06.log:[12:06:24] <Venemo> Mikaela: I can't deal with it right now, but can you please ping me sometime next week?
2015-08-06.log:[12:06:36] <Mikaela> if I remember, sure
```

**Comment by jpnurmi** [comment]
The first and easy step is to disable "local echo" of sent messages when the echo-message capability is active (https://github.com/communi/communi-desktop/commit/ab182a7541f3778e31f818b2a672e4573df1ee86). The side-effect is that your own sent messages will appear with a delay.

The second a bit more involved step is to show sent messages in gray "pending" state until the message gets echoed back (https://github.com/communi/communi-desktop/commit/bf908bf274c10ac81d52c38482fb9db4b53846ff).

**Comment by Mikaela** [comment]
I thought it had something to do with `sed -i 's/znc.in\//g`...

**Comment by jpnurmi** [comment]
Sorry, you're right. So the first step was actually already done, except that it just uses the old capability name which this bug report is about. Consider that step two as a nice future improvement idea, though. ;)

**Comment by Thaodan** [comment]
Like this?
https://github.com/Thaodan/communi-sailfish/commit/5d61f3e2849de025cad97b27c79db3138ec2259d

Did I miss something?

**Comment by Thaodan** [comment]
Fixed by: https://github.com/communi/communi-sailfish/commit/275a777c4b61b17ae02ab849f85c1f9711c09f90
