### ISSUE TITLE
Communi Sailfish crashes often when user is whoised or network is cloned.

### ISSUE THREAD

**Issue by Mikaela** [communi/communi-sailfish#117]
How I reproduced the whois crashing just now:
- `/whois Nikashi`
- `/whois jpnurmi`

Network cloning crashing I didn't test now, but I have reported it at IRC and it's unlikely to be fixed as there haven't been new versions.

**Comment by jpnurmi** [comment]
Updating the libcommuni submodule helps. The whois -related crash was fixed in https://github.com/communi/libcommuni/commit/1e20da6ab3de8669822311ec5f4b31f171897124.

**Comment by Thaodan** [comment]
Fixed in https://github.com/communi/communi-sailfish/commit/bd9019d21ade91ca460211d99678de13062c4639
