### ISSUE TITLE
WeeChat relay protocol & SSH tunnel support

### ISSUE THREAD

**Issue by Mikaela** [communi/communi-sailfish#125]
As there is issue about Quassel support (https://github.com/communi/communi-sailfish/issues/73) I thought I could open this.
- Documentation: https://weechat.org/files/doc/stable/weechat_relay_protocol.en.html

It doesn't require SSH tunnel support, but WeeChat-Android (WeeChat relay client for Android) supports it and it avoids the need of opening a port as you can just SSH tunnel to plain text port.

**Comment by lyro** [comment]
+1

Currently I'm using the irc-relay protocol of weechat together with [sailautossh](https://openrepos.net/content/fifr/sailautossh) for creating an ssh-tunnel on-the-fly, which works pretty well. This combination works reasonably well, but true weechat support would be better, of course ;)

**Comment by espritlibre** [comment]
@lyro I'm interessing about your solution ?

How that's work ? I want to acces to a remote weechat client from my communi.

Do you use relay feature in weechat to connect to it throught the communi client ?

Thanks for help.

**Comment by lyro** [comment]
@espritlibre Yes, I'm using the relay feature.

**Comment by Venemo** [comment]
I believe neither of the communi authors have the resources to implement full-blown WeeChat support at this time. If someone feels up to the task, you are welcome to submit a pull request.

**Comment by espritlibre** [comment]
I just try to use weechat relay and communi but that's KO.

In weechat i configure 

/relay add weechat 9001
/set relay.network.password ********

And in communi I use IP of server and port and the pass specify..

With glowing-bear.org it's OK but circle turn and turn with communi and not list a channel.

Do you see a problem ?

Thanks

**Comment by Mikaela** [comment]
WeeChat Relay supports two protocols: IRC & Relay Protocol.

The IRC relay should work as Communi Sailfish is a IRC client, but it's limited to only iRC buffers and probably single network per IRC relay.

This request is about the WeeChat Relay protocol which relays everything including core buffer, script buffers and all networks.

**Comment by espritlibre** [comment]
OK, I just understood that when i read /relay help ...
And for my usage i had to use a relay weechat
So +1 for me for support weechat relay

**Comment by rburchell** [comment]
Realise that I never commented here. I had some work started on this:

https://github.com/rburchell/communi-desktop/commits/master-weechat

The part that was "hard" and missing was UI for configuring these sort of connections. A relay connection multiplexes multiple server connections, and AFAIR Communi doesn't really expect that: assumes a single server is a single connection. That is an unsolved problem, and I'm not sure when/if I'll get back to do that.

I imagine that this should somehow create virtual connections from everything on the relay connection. That seems the most ideal UI, even if it isn't the easiest to achieve.

**Comment by rburchell** [comment]
I would not recommend using that code without some audit/cleanup, btw. Protocol handling is always a nasty thing, and I don't think I did a full degree of due diligence in making sure it was safe.

**Comment by Thaodan** [comment]
I close this here. I doubt we implement things like this as we removed the quassel support and will clean up the mess it caused.
