### ISSUE TITLE
Crash if trying to clone a cloned server

### ISSUE THREAD

**Issue by Ingvix** [communi/communi-sailfish#128]
As the title states. Now I can clone my old servers I once cloned but at least if cloning right away the one you just cloned the app crashes.

**Comment by Venemo** [comment]
Please provide the exact steps of how to reproduce this issue.

**Comment by Ingvix** [comment]
@Venemo Clone a server in the first page and clone that server you just cloned and then it crashes.

**Comment by Thaodan** [comment]
Doesn't happen or at least not anymore, closing.
