### ISSUE TITLE
Let user hide channel topic messages

### ISSUE THREAD

**Issue by lyro** [communi/communi-sailfish#131]
When entering a channel several control messages are shown: topic of the channel, who set the topic, the "own" join/rejoin message. The point is if the client reconnects to a server (happens frequently if you are on mobile connections), it rejoins all channels and those messages a shown again (in a low frequency channel the whole buffer is filled with these identical messages,  because the channel topic does not change very often).

There should be an option to hide these topic messages as there is for join/part messages.

**Comment by kimmoli** [comment]
+1

**Comment by Thaodan** [comment]
Merged in a650fe92990a62567cdbda1e95163d5994d19f35
The other issue is lated in #140
