### ISSUE TITLE
Nick already in use trigger Sailfish X reboot

### ISSUE THREAD

**Issue by Zastin** [communi/communi-sailfish#135]
When I am connecting quakenet and both my nicks are used, ask communi new nick. When I click accept new nick, communi freeze and second later Sailfish X reboot. Im not sure if problem is in Sailfish X or communi.

Also I have this problem: https://github.com/communi/communi-sailfish/issues/134

Sailfish version is 2.1.3.7, phone Sony Xperia X and communi version 0.9

**Comment by Venemo** [comment]
Unfortunately we don't have hardware to test with Sailfish X. But obviously it should NOT cause the OS to reboot. I asked for help on the mailing list, I hope we will see some hints.

**Comment by Venemo** [comment]
Let's track the problem in #134 and close this ticket.
