### ISSUE TITLE
Communi running in backround trigger sailfish x reboot

### ISSUE THREAD

**Issue by Zastin** [communi/communi-sailfish#136]
When communi is running in backround my phone reboot itself one or twice time in a day. When communi is not running in backround my phone didn't reboot itself. 

Im not sure if problem is in Sailfish X or communi.

Sailfish version is 2.1.3.7, phone Sony Xperia X and communi version 0.9.

Also I have this #135 and this #134 problem.

**Comment by Venemo** [comment]
Unfortunately we don't have hardware to test with Sailfish X. But obviously it should NOT cause the OS to reboot. I asked for help on the mailing list, I hope we will see some hints.

**Comment by Venemo** [comment]
Let's track the problem in #134 and close this ticket.
