### ISSUE TITLE
Duplicate self messages when connecting to a bouncer (ZNC)

### ISSUE THREAD

**Issue by ryanrms** [communi/communi-sailfish#137]
Don't know if this is for communi-sailfish or would be better raised in the main libcommuni github

Steps to reproduce:
1.  Connect to ZNC
2. Send a message
3.  Message sends, and then communi receives that message again from the bouncer, showing duplicate messages

This doesn't seem to be related to having another client connected to ZNC, I closed weechat on my computer and was still getting duplicate self messages.

Workaround:
1. Ignore your own nick
Messages still show up from you but you don't get a duplicate.

**Comment by ryanrms** [comment]
I downloaded communi-desktop from the AUR on my Arch desktop, and it doesn't have this problem.  So it looks to be an issue with the Sailfish version.

**Comment by ryanrms** [comment]
should note that this only happens with the openrepos version.  The Jolla store version works fine.  I'd really like to use the more updates ans featureful openrepos version though.

**Comment by Venemo** [comment]
Why do you use the openrepos version? IIRC we never uploaded this app to openrepos, and am not sure who did.

**Comment by ryanrms** [comment]
Sorry I just found it first.  The Jolla store version works fine, I’ll use that.  One question though, for one of my servers (Freenode) the user list is unavailable in all channels. On my other ZNC server (Rizon) the user list works fine, the lack of user list on freenode is why I thought the openrepo version was better. Do you think this is an issue with my ZNC settings, or communi’s?

**Comment by Thaodan** [comment]
@Venemo  thats my upload. I think there's some regression here.
The buffer playback it self don't works really.

**Comment by Thaodan** [comment]
No problem.
Look at my fork here. 
The branch that it's on obs/openrepos is lyro_merge.
I suspect some changes in the core of communi that broke the app 

Am 12. September 2018 11:23:20 MESZ schrieb "Timur Kristóf" <notifications@github.com>:

**Comment by Venemo** [comment]
Thanks @Thaodan I will probably be able to take a look next week.

**Comment by Thaodan** [comment]
I suspect some changes in the shared module.

**Comment by Thaodan** [comment]
Should be fixed by:
https://github.com/communi/communi-sailfish/commit/275a777c4b61b17ae02ab849f85c1f9711c09f90

**Comment by Thaodan** [comment]
Fixed by https://github.com/communi/communi-sailfish/commit/275a777c4b61b17ae02ab849f85c1f9711c09f90
