### ISSUE TITLE
Hide command output generated by other clients

### ISSUE THREAD

**Issue by llewelld** [communi/communi-sailfish#144]
I have both IRC and HexChat connected to the same ZNC server. **HexChat*** will periodically send /WHO requests, the output of which gets shown by IRC. This makes channels with many users difficult to use, because the conversation is periodically interrupted by the list.

As a user, it would be useful to have an option to mask this output out, so that the conversation isn't interrupted.

On some channels I just see "End of /WHO list" which isn't so bad, but on others this is preceded by the full list of users on the channel.

I can't give a screenshot of the latter because I only experience it in private channels, but here's a screenshot of the less severe version:

**\* Edit 15/3/2021: This should have said "Communi". It works fine on HexChat, but I experience this problem on communi.**
 
![irc-who-list](https://user-images.githubusercontent.com/1446122/72246879-6756e480-35fc-11ea-9a3d-bc4526564daa.png)

**Comment by Thaodan** [comment]
Have you asked how this is handled by other clients such as Hexchat? I assume this is standard behaiviour as [circe[(https://github.com/jorgenschaefer/circe) does the same.

**Comment by Thaodan** [comment]
Did you try to use https://wiki.znc.in/Route_replies?

**Comment by llewelld** [comment]
Edited original report to make clear that this problem is with Communi rather than HexChat.

**Comment by llewelld** [comment]
> Did you try to use https://wiki.znc.in/Route_replies?

After testing it all day with this enabled, I see plenty of "End of /WHO list" entries, but none of the channels are spammed with the contents of the WHO list, so as far as I'm concerned, this fixes it for me. Thanks @Thaodan!

I'll therefore close this as resolved/invalid.
